### ISSUE TITLE
Save one-file archive to filesystem

### ISSUE THREAD

**Issue by basilesimon** [digitalevidencetoolkit/deptoolkit-node-api#28]
Kind of hoping that [MHTML is where it's at](https://github.com/gildas-lormeau/SingleFile)

**Comment by nikonikoniko** [comment]
[this issue](https://github.com/gildas-lormeau/SingleFile/issues/267) led me to [this explanation](https://github.com/gildas-lormeau/SingleFile/wiki/How-to-integrate-the-API-of-SingleFile-into-an-extension)

**Comment by nikonikoniko** [comment]
possibly related, it seems that while firefox might be able to _save_ mhtml through a plugin like singlefile, it might not be able to open it: https://en.wikipedia.org/wiki/MHTML#Firefox
